packages:
  - "packages/**"
  - "shared/**"

allowBuilds:
  "@carbon/icons": false
  "@parcel/watcher": false
  "@tsparticles/engine": false
  core-js: false
  esbuild: false
  vue-demi: false

minimumReleaseAgeExclude:
  - "@herodotus/api"
  - "@herodotus/core"
  - "@herodotus/framework"
  - "vite"
  - '@vue/compiler-core'
  - '@vue/compiler-dom'
  - '@vue/compiler-sfc'
  - '@vue/compiler-ssr'
  - '@vue/reactivity'
  - '@vue/runtime-core'
  - '@vue/runtime-dom'
  - '@vue/server-renderer'
  - '@vue/shared'
